all:
  children:
    vault:
      hosts:
        vault-test-01:
          ansible_host: 10.255.107.46
        vault-test-02:
          ansible_host: 10.255.107.47
        vault-test-03:
          ansible_host: 10.255.107.48
