vault_config_file: /etc/vault.d/vault.hcl
vault_ui: true
vault_disable_mlock: false
vault_listener_tcp_address: "0.0.0.0:8200"
vault_listener_cluster_address: "0.0.0.0:8201"
vault_api_addr: "https://{{ vault_api_vip | default(hostvars[inventory_hostname].ansible_host | default(inventory_hostname)) }}:8200"
vault_cluster_addr: "https://{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}:8201"
vault_tls_cert_file: /etc/vault.d/tls/vault.crt
vault_tls_key_file: /etc/vault.d/tls/vault.key
vault_tls_ca_file: /etc/vault.d/tls/ca.crt
vault_tls_disable_client_certs: true
vault_require_tls_files: true
vault_raft_path: "{{ vault_data_dir | default('/opt/vault') }}/raft"
vault_raft_retry_join: []
vault_service_name: vault
vault_bin_path: /usr/local/bin/vault
vault_manage_firewalld: "{{ vault_firewalld_managed | default(true) }}"
vault_config_api_source_cidrs: "{{ vault_allowed_api_cidrs | default([]) }}"
vault_config_cluster_source_cidrs: []
vault_config_firewall_strict: true
vault_config_postcheck_enabled: true
