vault_version: "1.16.2"
vault_download_checksum: ""
vault_api_addr: "{{ vault_public_url }}"
vault_listener_tcp_address: "0.0.0.0:8200"
vault_listener_cluster_address: "0.0.0.0:8201"
vault_tls_cert_file: /etc/vault.d/tls/vault.crt
vault_tls_key_file: /etc/vault.d/tls/vault.key
vault_tls_ca_file: /etc/vault.d/tls/ca.crt
vault_tls_deploy_from_controller: true
vault_tls_controller_mode: bundle
vault_tls_controller_bundle_file: "{{ playbook_dir }}/../tls/vault.pem"
vault_tls_controller_bundle_as_ca: true
vault_bootstrap_enabled: false
vault_bootstrap_enable_audit_device: true
